//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPINFO
    {
        public string EmpID { get; set; }
        public string Imię { get; set; }
        public string Wiek { get; set; }
        public string Stan_Konta { get; set; }
    }
}
